### ISSUE TITLE
firefox support!

### ISSUE THREAD

**Issue by Fadyio** [jawerty/myAlgorithm#2]
Do you plan to make a Firefox version ?

**Comment by jawerty** [comment]
Yes! Working on it now hoping to be done by next week. Speaking of I’m going to add an Todo feature list to the readme.

**Comment by jawerty** [comment]
Firefix version added :) https://addons.mozilla.org/en-US/firefox/addon/myalgorithm/ and included in source @fadyio

**Comment by Fadyio** [comment]
Thank you I left 5 stars review
keep up the good work

**Comment by jawerty** [comment]
Thanks!
