### ISSUE TITLE
Discord invite is invalid, can't save customizations

### ISSUE THREAD

**Issue by GrindamN** [jawerty/myAlgorithm#3]
First, I would like to say thing project is awesome and really interesting. Would be interested to find more about. However it seems that your discord link is broken.

While I am at it, when using Chrome Version 103.0.5060.134 (Official Build) (64-bit) the settings that are changed do not work, they revert back to default one.

**Comment by jawerty** [comment]
Thanks I just updated the discord link in the readme to the proper one. As for the bug can you let me know which version of the extension you have?

**Comment by GrindamN** [comment]
@jawerty Hey, thanks for quick answer. It is the one from Chrome store, installed it few hours ago. 

Noticed this in console when observing the possible errors:
Error in event handler: TypeError: Cannot read properties of undefined (reading 'disableAlgorithm')
    at chrome-extension://imkkppomfljhnaaolbdgffnleejjbpjn/background.js:133:60

**Comment by jawerty** [comment]
Great yes I know this error I’ll take care of it as soon as possible

**Comment by jawerty** [comment]
In the meantime you can try cloning this repo with the latest version to fix. but i will submit a new version by tomorrow anyway and keep you updated

**Comment by jawerty** [comment]
Fix has been updated on the chrome store

**Comment by GrindamN** [comment]
It works fine. Although the loading for new topics can take while.

**Comment by jawerty** [comment]
Yea working on fixing that. Will likely cap the feed to 10 items and fix the size of the topics as well
